### ISSUE TITLE
Version of reinvent-scoring

### ISSUE THREAD

**Issue by iwatobipen** [MolecularAI/reinvent-scoring#2]
Dear developer,

Thanks for great work for chemoinformatics.
Recently reinvent v3.1 is released and reinvent-scoring v0.0.57 is used in it. But the version of the repo is 0.0.41.
Do you have the plan to update the version?
Thanks,

Taka

**Comment by j3mdamas** [comment]
@iwatobipen in PyPi the versions up to 0.0.57 are available: https://pypi.org/project/reinvent-scoring/#history
Did you face any error when upgrading?

**Comment by iwatobipen** [comment]
Hi @j3mdamas ,
Thanks for your suggestion. Sure I knew and could run new version of rreinvent ;)
However I would like to add additional own scoring function to reinvent-scoring so I'll be happy if the version of repo will be updated.
Thanks,
